version: '3'

services:
  app:
    build:
      context: app
      dockerfile: ./BACK/Dockerfile
    container_name: 'API'
    depends_on:
      - database
    command: "npm run start"
    environment:
      - env_var_name=${VARIABLE_NAME}
    ports:
      - "5000:5000"
    volumes:
      - ./BACK:/home/node/app

  client:
    build:
      context: client
      dockerfile: ./FRONT/Dockerfile
    container_name: 'Client'
    command: "yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./FRONT:/home/node/app

  database:
    image: postgres
    container_name: 'database'
    restart: always
    environment:
      - env_var_name=${VARIABLE_NAME}
    ports:
          - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local